---
title: "p8105_hw2_raj2152"
author: "Rachelle Juan"
date: "10/9/2021"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

# Problem 1

Importing and cleaning the Mr. Trash Wheel sheet.
```{r}
trashwheel_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N408"
  ) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(across(sports_balls, round, 0))
```

Read and clean precipitation data for 2018 and 2019. 
```{r}
precip18_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    range = "A2:B14"
  ) %>% 
  janitor::clean_names() %>% 
  rename(total_precipitation = total) %>% 
  mutate(year = "2018") %>% 
  drop_na(total_precipitation)  
  

precip19_df = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2019 Precipitation",
    range = "A2:B14"
  ) %>% 
  janitor::clean_names() %>% 
  rename(total_precipitation = total) %>% 
  mutate(year = "2019") %>% 
  drop_na(total_precipitation) 
```


